import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import importPlugin from 'eslint-plugin-import';
import betterTailwindcss from 'eslint-plugin-better-tailwindcss';
import eslintComments from '@eslint-community/eslint-plugin-eslint-comments';
import tseslint from 'typescript-eslint';
import { defineConfig, globalIgnores } from 'eslint/config';

// Type-checked + a11y + import-cycle hardening, per Issue #1.
// Three separate file groups, each with the right TS project for type-aware rules:
//   - src/**/*.{ts,tsx}     → app code, parsed against tsconfig.app.json (DOM lib, jsx, vitest)
//   - api/**/*.ts           → Vercel serverless handlers, parsed against tsconfig.api.json (Node, no DOM)
//   - vite/playwright/scripts → tooling, parsed against tsconfig.node.json or untyped
//
// No rule suppressions anywhere in the codebase by policy (see PLAN.md, durable preference).
export default defineConfig([
  globalIgnores([
    'dist',
    'node_modules',
    '.claude/**',
    'tests/visual/**',
    'fog-and-frontier/**',
    'playwright-report/**',
    // Generated by `vitest run --coverage` (istanbul report assets ship with
    // their own `/* eslint-disable */`). A build artifact like dist/, never
    // authored — and the repo-wide no-use rule below would otherwise flag it.
    'coverage',
    'public/**',
    '**/*.sqlite',
    // Generated by graphql-codegen (client-preset). Treated as a build
    // artifact, not authored code — excluded from linting like dist/.
    'src/gql/**',
  ]),

  // Repo-wide: turn the "no rule suppressions" policy into a lint error.
  // `no-use` bans every inline ESLint control comment (eslint-disable,
  // eslint-disable-next-line, eslint-enable, …) so a violation can't be
  // silenced in-line. The sanctioned escape hatch stays the narrow,
  // file-scoped overrides in this config — those are configuration, not
  // comments, so they are unaffected. `@ts-ignore` / `@ts-expect-error` are
  // already blocked by @typescript-eslint's ban-ts-comment via
  // recommendedTypeChecked. No `files` key: this applies to every linted
  // file; the generated src/gql/** output (which carries a codegen
  // `/* eslint-disable */`) is already in globalIgnores above, so it is never
  // processed and never trips this rule.
  {
    plugins: {
      '@eslint-community/eslint-comments': eslintComments,
    },
    rules: {
      '@eslint-community/eslint-comments/no-use': 'error',
    },
  },

  // App code (browser + tests). Type-aware via tsconfig.app.json.
  // Tailwind v4 class-conflict linting via eslint-plugin-better-tailwindcss
  // (Phase C of Issue #1). We deliberately do NOT enable
  // `enforce-consistent-class-order` — that's a Prettier-flavored rule and
  // we don't use Prettier in this repo. Instead we run the correctness rules
  // (`no-conflicting-classes`, `no-duplicate-classes`) which catch the cases
  // the issue called out: `text-sm text-lg`, `p-3 p-4`, duplicated classes.
  // The v4 entry point is `src/index.css` (CSS-based config, no JS config file).
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      jsxA11y.flatConfigs.recommended,
      importPlugin.flatConfigs.recommended,
      importPlugin.flatConfigs.typescript,
    ],
    plugins: {
      'better-tailwindcss': betterTailwindcss,
    },
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        project: ['./tsconfig.app.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      'import/resolver': {
        typescript: { project: './tsconfig.app.json' },
      },
      'better-tailwindcss': {
        entryPoint: 'src/index.css',
      },
    },
    rules: {
      'import/no-cycle': ['error', { ignoreExternal: true }],
      'import/no-unresolved': ['error', { ignore: ['^virtual:'] }],
      'import/no-named-as-default-member': 'off',
      'better-tailwindcss/no-conflicting-classes': 'error',
      'better-tailwindcss/no-duplicate-classes': 'error',
    },
  },

  // Vercel serverless handlers. Node lib, no DOM, no JSX. Type-aware via tsconfig.api.json.
  {
    files: ['api/**/*.ts'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      importPlugin.flatConfigs.recommended,
      importPlugin.flatConfigs.typescript,
    ],
    languageOptions: {
      globals: globals.node,
      parserOptions: {
        project: ['./tsconfig.api.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      'import/resolver': {
        // api/*.ts imports siblings with a `.js` extension (NodeNext-style),
        // which the TS resolver handles automatically.
        typescript: { project: './tsconfig.api.json' },
      },
    },
    rules: {
      'import/no-cycle': ['error', { ignoreExternal: true }],
      'import/no-named-as-default-member': 'off',
    },
  },

  // Gemini output-quality eval harness (issue #122). Node lib, no DOM, no JSX.
  // Type-aware via tsconfig.eval.json. Mirrors the api/**/*.ts block.
  {
    files: ['eval/**/*.ts'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      importPlugin.flatConfigs.recommended,
      importPlugin.flatConfigs.typescript,
    ],
    languageOptions: {
      globals: globals.node,
      parserOptions: {
        project: ['./tsconfig.eval.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      'import/resolver': {
        // eval/*.ts imports siblings with a `.js` extension (NodeNext-style),
        // which the TS resolver handles automatically.
        typescript: { project: './tsconfig.eval.json' },
      },
    },
    rules: {
      'import/no-cycle': ['error', { ignoreExternal: true }],
      'import/no-named-as-default-member': 'off',
    },
  },

  // Tooling config files. Node globals, but not type-aware — these files aren't
  // part of any tsconfig include and don't need cross-file project analysis.
  {
    files: ['vite.config.ts', 'playwright.config.ts', 'codegen.ts'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: { globals: globals.node },
  },

  // Plain Node scripts (smoke gate, db snapshot, seed). Untyped JS.
  {
    files: ['scripts/**/*.{js,mjs}', 'eslint.config.js'],
    extends: [js.configs.recommended],
    languageOptions: { globals: globals.node },
  },
]);
